### ISSUE TITLE
Recording Stops working after sometime.

### ISSUE THREAD

**Issue by HaydoZV2** [dominikks/discord-soundboard-bot#3] opened 2023-09-07 11:30 UTC
Recording will work for a few records (~3) before it becomes choppy and the recorded file goes from 60 seconds to 100+seconds.

**Log shows:** 
thread 'rocket-worker-thread' panicked at 'Missing element in Deque', src/discord/recorder.rs:202:34

Each time the recording button is clicked.

**Comment by dominikks** [comment] 2023-09-10 20:35
Thanks for raising the issue! I'll try to look into it this week and hopefully find a fix.

**Comment by dominikks** [comment] 2023-09-12 00:26
Unfortunately, I was not able to reproduce the error in my testing. Maybe it only occurs when there are multiple users in the channel?

However, I have a notion of where this error might come from and have pushed an update to the `development` branch. You can try it by switching the Docker image from `ghcr.io/dominikks/discord-soundboard-bot` to `ghcr.io/dominikks/discord-soundboard-bot:development`. Let me know if that solves the problem!

**Comment by Zorxe** [comment] 2023-09-14 08:01
I have same issue, switching to development build solved this _'Missing element in Deque', src/discord/recorder.rs:202:34_ 

Recordings still choppy though which can be reproduced from both API & Discord.

**Comment by dominikks** [comment] 2023-09-21 21:28
The issue seems to be difficult to reproduce for me. I managed it once, but after reconnecting the soundboard it never occurred again. This makes me think that it might have something to do with how the bot connects to the voice channel.

Could you set the environment variable `RUST_LOG=discord_soundboard_bot=TRACE` and capture some logs when the issue occurs? Maybe this will give me a hint on what is going wrong.

**Comment by Zorxe** [comment] 2023-09-22 13:02
Attached logs as requested. Was able to reproduce choppy recording after 3 recordings.

[soundboard_logs.log](https://github.com/dominikks/discord-soundboard-bot/files/12700966/soundboard_logs.log)

**Comment by dominikks** [comment] 2023-09-22 19:04
Thanks! From your logs it seems like the bot receives all audio packets twice:
```
soundboard_1  | 2023-09-22T12:50:51.365179Z TRACE act{guild_id=268853305331941379}: discord_soundboard_bot::discord::recorder: Audio packet sequence 25214 has 3840 bytes (decompressed from 160) ssrc=230595
soundboard_1  | 2023-09-22T12:50:51.365451Z TRACE act{guild_id=268853305331941379}: discord_soundboard_bot::discord::recorder: Extended existing recording total_len=3840
soundboard_1  | 2023-09-22T12:50:51.365594Z TRACE act{guild_id=268853305331941379}: discord_soundboard_bot::discord::recorder: Audio packet sequence 25214 has 3840 bytes (decompressed from 160) ssrc=230595
soundboard_1  | 2023-09-22T12:50:51.365678Z TRACE act{guild_id=268853305331941379}: discord_soundboard_bot::discord::recorder: Added new recording recording_count=262 len=1920
soundboard_1  | 2023-09-22T12:50:51.391199Z TRACE act{guild_id=268853305331941379}: discord_soundboard_bot::discord::recorder: Audio packet sequence 25215 has 3840 bytes (decompressed from 165) ssrc=230595
soundboard_1  | 2023-09-22T12:50:51.391468Z TRACE act{guild_id=268853305331941379}: discord_soundboard_bot::discord::recorder: Extended existing recording total_len=3840
soundboard_1  | 2023-09-22T12:50:51.391602Z TRACE act{guild_id=268853305331941379}: discord_soundboard_bot::discord::recorder: Audio packet sequence 25215 has 3840 bytes (decompressed from 165) ssrc=230595
soundboard_1  | 2023-09-22T12:50:51.391687Z TRACE act{guild_id=268853305331941379}: discord_soundboard_bot::discord::recorder: Added new recording recording_count=263 len=1920
``` 

The sequence number is 25214 twice and then 25215 twice. This does not happen during my testing. I assume that this is the reason for the glitches.

I've added some logic to detect and discard duplicate audio packets in the latest `development` image. I hope that this fixes the issue!

**Comment by Zorxe** [comment] 2023-09-23 10:29
Till now it's still recording well. As for the log already produced it.

`2023-09-23T10:28:10.744554Z TRACE act{guild_id=268853305331941379}: discord_soundboard_bot::discord::recorder: Received duplicate audio packet, ignoring`

**Comment by dominikks** [comment] 2023-09-23 12:12
That's great to hear! I'll close the issue as resolved then.

**Closed** 2023-09-23 12:13 UTC
